task_config:
  task_name: "container_name_test"
  launch_type: "docker"
  workspace: "/workspace"
  default_shell: "/bin/bash"
  default_http_port: 80
  cmd_proxy_url: null  # 原proxy_url重命名为cmd_proxy_url
  env_vars: {}
  openai_api_key: null
  openai_base_url: null
  
  # 搜索和网页浏览功能默认禁用
  search_engine: ""
  web_proxy_url: ""

gym_container_config_list:
  - image_name: "80-20_test:latest"
    container_name: "80-20_test"
    host_port: 8021
    container_port: 8123
    container_ip: "172.17.0.5"  # 这个字段将逐步被container_name替代
    environment: {}
    volumes: {"./gym_workspace": {"bind": "/workspace", "mode": "rw"}}
    remove_on_close: false
    
  - image_name: "task_0008_2_test:latest"
    container_name: "task_0008_2_test"
    host_port: 8041
    container_port: 8123
    container_ip: "172.17.0.6"  # 这个字段将逐步被container_name替代
    environment: {}
    volumes: {"./gym_workspace": {"bind": "/workspace", "mode": "rw"}}
    remove_on_close: false

eval_container_config:
  image_name: "task_0008_2_test:latest"
  container_name: "eval_workspace"
  host_port: 8082
  container_port: 80
  container_ip: "127.0.0.1"
  environment: {}
  volumes: {"./eval_workspace": {"bind": "/workspace", "mode": "rw"}}
  remove_on_close: true 