
default:
  - api_key: "123" # OpenAI key
    organization: "123"
gpt-4-1106-preview: # only when using `model_name: gpt-4-1106-preview` which is AlpacaEval2's model name
    - "default" # this will append all the `default` configs
    - client_class: "openai.AzureOpenAI" # doesn't use the `openai.OpenAI` client class
      # the following are passed to the `AzureOpenAI` client class
      azure_deployment: "gpt-4o" # name of the latest GPT-4 turbo on azure change as needed
      api_key: "" # AzureOpenAI key
      azure_endpoint: ""
      api_version: ""